# Generated by Django 3.2.9 on 2023-04-26 06:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=30)),
                ('brand', models.CharField(max_length=30)),
                ('product_price', models.CharField(max_length=30)),
                ('product_category', models.CharField(default='', max_length=50)),
                ('product_description', models.TextField(default='', max_length=300)),
                ('product_image', models.ImageField(default='', upload_to='images/product_images')),
                ('ratings', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'all_products',
            },
        ),
    ]
