# Generated by Django 3.2.9 on 2023-05-07 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouseaddress',
            name='warehouse_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
