# Generated by Django 3.2.9 on 2023-04-26 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20230426_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_sub_subcategory',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.subsubcategory'),
        ),
    ]
