# Generated by Django 3.2.9 on 2023-05-10 05:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20230510_0201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consignment',
            old_name='company_warehouse',
            new_name='warehouse_address',
        ),
        migrations.RemoveField(
            model_name='consignment',
            name='product_brand_verification',
        ),
        migrations.AddField(
            model_name='consignment',
            name='scheduled_time',
            field=models.DateTimeField(default=''),
        ),
        migrations.AddField(
            model_name='consignment',
            name='seller_address',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.selleraddress'),
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=50)),
                ('product_brand_verification', models.FileField(default='', upload_to='files/verification_documents')),
                ('product_size', models.CharField(max_length=30)),
                ('product_color', models.CharField(default='', max_length=30)),
                ('product_price', models.CharField(max_length=30)),
                ('product_description', models.TextField(default='', max_length=300)),
                ('product_image1', models.ImageField(default='', upload_to='images/product_images')),
                ('product_image2', models.ImageField(default='', upload_to='images/product_images')),
                ('product_image3', models.ImageField(default='', upload_to='images/product_images')),
                ('product_image4', models.ImageField(default='', upload_to='images/product_images')),
                ('qc_pass_status', models.BooleanField(default=False)),
                ('company_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.warehouseaddress')),
                ('product_brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.brand')),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.category')),
                ('product_sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.subcategory')),
                ('product_sub_sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.subsubcategory')),
                ('seller_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.seller')),
            ],
        ),
    ]
