# Generated by Django 3.2.9 on 2023-04-26 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_product_product_sub_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerWarehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_warehouse_name', models.CharField(max_length=50)),
                ('s_warehouse_address', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'all_seller_warehouses',
            },
        ),
        migrations.AddField(
            model_name='seller',
            name='company_warehouse',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.warehouse'),
        ),
        migrations.AddField(
            model_name='seller',
            name='seller_warehouse',
            field=models.ManyToManyField(to='api.SellerWarehouse'),
        ),
    ]
