# Generated by Django 3.2.9 on 2023-05-10 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20230510_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consignment',
            name='scheduled_time',
            field=models.DateTimeField(default='', null=True),
        ),
    ]
