# Generated by Django 3.2.9 on 2023-05-10 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_consignment_scheduled_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='company_warehouse',
            new_name='warehouse_address',
        ),
    ]
