# Generated by Django 3.2.9 on 2023-04-26 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20230426_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerwarehouse',
            name='s_warehouse_address',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='warehouse_address',
            field=models.CharField(max_length=150),
        ),
    ]
