# Generated by Django 3.2.9 on 2023-05-10 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20230510_1118'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Listing',
        ),
    ]
