# Generated by Django 3.2.9 on 2023-05-03 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_selleraddress_street_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='selleraddress',
            old_name='area',
            new_name='postoffice',
        ),
        migrations.RenameField(
            model_name='selleraddress',
            old_name='city',
            new_name='town_or_city',
        ),
    ]
