# Generated by Django 3.2.9 on 2023-05-10 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_listing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='product_brand',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='product_category',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='product_sub_category',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='product_sub_sub_category',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='seller_name',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='warehouse_address',
        ),
        migrations.DeleteModel(
            name='Consignment',
        ),
        migrations.DeleteModel(
            name='Listing',
        ),
    ]
