# Generated by Django 3.2.9 on 2023-05-05 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
