# Generated by Django 3.2.9 on 2023-05-10 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_consignment_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='consignment',
            name='company_warehouse_address',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.warehouse'),
        ),
    ]
