# Generated by Django 3.2.9 on 2023-05-05 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_myuser_is_live'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='is_live',
        ),
    ]
