# Generated by Django 3.2.9 on 2023-05-10 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_consignment_warehouse_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='consignment',
            name='warehouse_address',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.warehouseaddress'),
        ),
    ]
