# Generated by Django 3.2.9 on 2023-05-05 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_myuser_is_live'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='is_live',
            field=models.BooleanField(default=False),
        ),
    ]
