# Generated by Django 3.2.9 on 2023-05-05 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_myuser_is_live'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='first_name',
            field=models.CharField(default='', max_length=255, verbose_name='first name'),
        ),
    ]
