# Generated by Django 3.2.9 on 2023-05-06 03:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0017_myuser_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='otp_verified',
            field=models.BooleanField(default='False'),
        ),
        migrations.AddField(
            model_name='seller',
            name='seller_mobile',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='seller',
            name='seller_otp',
            field=models.CharField(default='', max_length=6),
        ),
        migrations.AddField(
            model_name='seller',
            name='username',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
