# Generated by Django 3.2.9 on 2023-05-07 05:02

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('api', '0018_auto_20230506_0924'),
    ]

    operations = [
        migrations.CreateModel(
            name='IsLive',
            fields=[
            ],
            options={
                'verbose_name': 'Is Live',
                'verbose_name_plural': 'Is Live',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.permission',),
            managers=[
                ('objects', django.contrib.auth.models.PermissionManager()),
            ],
        ),
    ]
