# Generated by Django 3.2.9 on 2023-05-10 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20230510_1532'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ListingNew',
            new_name='ListingNew11',
        ),
    ]
