# Generated by Django 3.2.9 on 2023-05-10 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_rename_listingnew_listingnew11'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ListingNew11',
        ),
    ]
