# Generated by Django 3.2.9 on 2023-05-07 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_warehouseaddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouse',
            name='warehouse_address',
        ),
    ]
