# Generated by Django 3.2.9 on 2023-05-07 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20230507_1642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouseaddress',
            name='warehouse_name',
        ),
    ]
