# Generated by Django 3.2.9 on 2023-05-10 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_listingnew12'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ListingNew12',
        ),
    ]
