# Generated by Django 3.2.9 on 2023-05-07 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_remove_warehouseaddress_warehouse_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='company_warehouse',
        ),
    ]
