# Generated by Django 3.2.9 on 2023-05-10 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_listingnew'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consignment',
            name='scheduled_time',
        ),
        migrations.AddField(
            model_name='consignment',
            name='product_stock',
            field=models.IntegerField(null=True),
        ),
    ]
