# Generated by Django 3.2.9 on 2023-05-07 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_remove_seller_company_warehouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='company_warehouse',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.warehouse'),
        ),
        migrations.AddField(
            model_name='warehouseaddress',
            name='warehouse_name',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.warehouse'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='warehouse_name',
            field=models.CharField(default='', max_length=50, primary_key=True, serialize=False),
        ),
    ]
