# Generated by Django 3.2.9 on 2023-05-10 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_auto_20230510_1538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consignment',
            name='product_stock',
        ),
    ]
