# Generated by Django 3.2.9 on 2023-05-07 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_auto_20230507_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='id',
            field=models.CharField(default='', max_length=8),
        ),
    ]
