# Generated by Django 3.2.9 on 2023-05-10 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_remove_consignment_product_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='consignment',
            name='product_stock',
            field=models.IntegerField(null=True),
        ),
    ]
